// GENERATED by struct_census (CENSUS_EMIT=1) — the static-b fast kernel.
//
// The mask/expected constants describe byte positions of the round-1 b
// operand that the BLAKE3 circuit fixes independently of the witness
// inputs (const-one wires and structural zeros of linear constraints).
// They are ONLY a performance hint: every K-row checks
// `(b_word & MASK) == EXPECTED` and falls back to the generic row when
// the witness disagrees, so the kernel is bit-exact for any witness.
//
// Included by kernels/aarch64.rs via include!.

#[cfg(target_arch = "aarch64")]
pub(crate) static BSTATIC_MASKS: [[(u64, u64); 8]; 31] = [
    [
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
    ],
    [
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
    ],
    [
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xff00000000000000, 0xff00000000000000),
        (0x0000ffffffffffff, 0x0000ffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffff000000000000, 0xffff000000000000),
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffff000000000000, 0xffff000000000000),
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffff0000000000, 0xffffff0000000000),
        (0x00000000ffffffff, 0x00000000ffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffffff00000000, 0xffffffff00000000),
        (0x0000000000ffffff, 0x0000000000ffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffff000000, 0xffffffffff000000),
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffffffff000000, 0xffffffffff000000),
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffff0000, 0xffffffffffff0000),
        (0x00000000000000ff, 0x00000000000000ff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffffffffffff00, 0xffffffffffffff00),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xff00000000000000, 0xff00000000000000),
        (0x0000ffffffffffff, 0x0000ffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffff000000000000, 0xffff000000000000),
    ],
    [
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffff0000000000, 0xffffff0000000000),
        (0x00000000ffffffff, 0x00000000ffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffff0000000000, 0xffffff0000000000),
    ],
    [
        (0x00000000ffffffff, 0x00000000ffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffff00000000, 0xffffffff00000000),
        (0x0000000000ffffff, 0x0000000000ffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffff000000, 0xffffffffff000000),
    ],
    [
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffff0000, 0xffffffffffff0000),
        (0x00000000000000ff, 0x00000000000000ff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffff0000, 0xffffffffffff0000),
    ],
    [
        (0x00000000000000ff, 0x00000000000000ff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffffff00, 0xffffffffffffff00),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xff00000000000000, 0xff00000000000000),
        (0x0000ffffffffffff, 0x0000ffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xff00000000000000, 0xff00000000000000),
        (0x0000ffffffffffff, 0x0000ffffffffffff),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffff000000000000, 0xffff000000000000),
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffff0000000000, 0xffffff0000000000),
        (0x00000000ffffffff, 0x00000000ffffffff),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffff00000000, 0xffffffff00000000),
        (0x0000000000ffffff, 0x0000000000ffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffff00000000, 0xffffffff00000000),
        (0x0000000000ffffff, 0x0000000000ffffff),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffff000000, 0xffffffffff000000),
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffff0000, 0xffffffffffff0000),
        (0x00000000000000ff, 0x00000000000000ff),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffffff00, 0xffffffffffffff00),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffffff00, 0xffffffffffffff00),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xff00000000000000, 0xff00000000000000),
        (0x0000ffffffffffff, 0x0000ffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0xffff000000000000, 0xffff000000000000),
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffff000000000000, 0xffff000000000000),
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0xffffff0000000000, 0xffffff0000000000),
        (0x00000000ffffffff, 0x00000000ffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffff00000000, 0xffffffff00000000),
        (0x0000000000ffffff, 0x0000000000ffffff),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffff000000, 0xffffffffff000000),
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffff000000, 0xffffffffff000000),
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffff0000, 0xffffffffffff0000),
        (0x00000000000000ff, 0x00000000000000ff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffffff00, 0xffffffffffffff00),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xff00000000000000, 0xff00000000000000),
        (0x0000ffffffffffff, 0x0000ffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffff000000000000, 0xffff000000000000),
        (0x000000ffffffffff, 0x000000ffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffff0000000000, 0xffffff0000000000),
        (0x00000000ffffffff, 0x00000000ffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffff0000000000, 0xffffff0000000000),
        (0x00000000ffffffff, 0x00000000ffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffffff00000000, 0xffffffff00000000),
        (0x0000000000ffffff, 0x0000000000ffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffff000000, 0xffffffffff000000),
        (0x000000000000ffff, 0x000000000000ffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffffffffff0000, 0xffffffffffff0000),
        (0x00000000000000ff, 0x00000000000000ff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xffffffffffff0000, 0xffffffffffff0000),
        (0x00000000000000ff, 0x00000000000000ff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
    ],
    [
        (0xffffffffffffff00, 0xffffffffffffff00),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0x00ffffffffffffff, 0x00ffffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xff00000000000000, 0xff00000000000000),
    ],
    [
        (0x0000ffffffffffff, 0x0000ffffffffffff),
        (0x0000000000000000, 0x0000000000000000),
        (0x0000000000000000, 0x0000000000000000),
        (0xff00000000000000, 0xff00000000000000),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
        (0xffffffffffffffff, 0xffffffffffffffff),
    ],
    [
        (0xffffffffffffffff, 0x0001ffffffffffff),
        (0xffffffffffffffff, 0x0000000000000000),
        (0xffffffffffffffff, 0x0000000000000000),
        (0xffffffffffffffff, 0x0000000000000000),
        (0xffffffffffffffff, 0x0000000000000000),
        (0xffffffffffffffff, 0x0000000000000000),
        (0xffffffffffffffff, 0x0000000000000000),
        (0xffffffffffffffff, 0x0000000000000000),
    ],
];

#[cfg(target_arch = "aarch64")]
fn bstatic_partials(inv_table: &InvNttTableByteSingleGf8) -> &'static [[u8; 64]; 248] {
    static PARTIALS: std::sync::OnceLock<Box<[[u8; 64]; 248]>> = std::sync::OnceLock::new();
    PARTIALS.get_or_init(|| {
        let mut out = Box::new([[0u8; 64]; 248]);
        for blk in 0..31 {
            for k in 0..8 {
                let (_m, e) = BSTATIC_MASKS[blk][k];
                let mut f = [F8::ZERO; 64];
                inv_table.apply(&e.to_le_bytes(), &mut f);
                out[blk * 8 + k] = core::array::from_fn(|i| f[i].0);
            }
        }
        out
    })
}

#[cfg(target_arch = "aarch64")]
static BSTATIC_ARM_LIVE: [bool; 31] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true];

/// Guarded static-b variant of [`shift_reduce_inner_ab_fused_neon`].
/// Returns `false` when this (w, b_med) position has no static plan, in
/// which case the caller must run the generic kernel.
#[cfg(target_arch = "aarch64")]
#[allow(clippy::too_many_lines)]
pub(crate) fn shift_reduce_inner_ab_bstatic<const FAST: bool>(
    a_packed: &[u8],
    b_packed: &[u8],
    inv_table: &InvNttTableByteSingleGf8,
    chunk_byte_base: usize,
    b_med: usize,
    w: usize,
    context: StaticBContext,
    out: &mut [u8; 64],
    nt_store: bool,
) -> bool {
    use crate::field::gf2_8::neon::gf8_reduce_vec16;
    use core::arch::aarch64::*;
    if w > 1 || (w == 1 && b_med >= 15) {
        return false;
    }
    let blk = w * 16 + b_med;
    if !BSTATIC_ARM_LIVE[blk] {
        return false;
    }
    let partials = match context {
        StaticBContext::Prepared { partials, .. } => partials,
        StaticBContext::LegacyPerCall => bstatic_partials(inv_table),
    };
    let byte_base_b = chunk_byte_base + b_med * N_CHUNKS * 8;
    let table_base = inv_table.data_ptr();
    let half_swapped_table_base = inv_table.half_swapped_data_ptr();
    // `x^4`-scaled twin of the two images above; only read on the FAST path,
    // where the K ≥ 4 rows take their `a`-side transform out of it so the
    // `x^4` part of the `x^K` weight costs no instructions.
    let scaled_base = inv_table.scaled_x4_data_ptr();
    let scaled_half_swapped_base = inv_table.scaled_x4_half_swapped_data_ptr();
    unsafe {
        let mut acc0_lo = vdupq_n_u16(0);
        let mut acc0_hi = vdupq_n_u16(0);
        let mut acc1_lo = vdupq_n_u16(0);
        let mut acc1_hi = vdupq_n_u16(0);
        let mut acc2_lo = vdupq_n_u16(0);
        let mut acc2_hi = vdupq_n_u16(0);
        let mut acc3_lo = vdupq_n_u16(0);
        let mut acc3_hi = vdupq_n_u16(0);
        macro_rules! k_generic {
            ($k:literal) => {{
                let off = byte_base_b + $k * N_CHUNKS;
                if FAST {
                    fused_apply_one_k_fast::<{ $k & 1 }, { $k & 2 != 0 }>(
                        if $k & 4 != 0 { scaled_base } else { table_base },
                        if $k & 4 != 0 {
                            scaled_half_swapped_base
                        } else {
                            half_swapped_table_base
                        },
                        table_base,
                        half_swapped_table_base,
                        a_packed.as_ptr().add(off),
                        b_packed.as_ptr().add(off),
                        &mut acc0_lo,
                        &mut acc0_hi,
                        &mut acc1_lo,
                        &mut acc1_hi,
                        &mut acc2_lo,
                        &mut acc2_hi,
                        &mut acc3_lo,
                        &mut acc3_hi,
                    );
                } else {
                    fused_apply_one_k::<$k>(
                        table_base,
                        half_swapped_table_base,
                        a_packed.as_ptr().add(off),
                        b_packed.as_ptr().add(off),
                        &mut acc0_lo,
                        &mut acc0_hi,
                        &mut acc1_lo,
                        &mut acc1_hi,
                        &mut acc2_lo,
                        &mut acc2_hi,
                        &mut acc3_lo,
                        &mut acc3_hi,
                    );
                }
            }};
        }
        macro_rules! k_static {
            ($k:literal, [$(($j0:literal, $j1:literal)),*], [$($js:literal),*]) => {{
                let off = byte_base_b + $k * N_CHUNKS;
                let a_row = a_packed.as_ptr().add(off);
                let b_row = b_packed.as_ptr().add(off);
                let (m, e) = BSTATIC_MASKS[blk][$k];
                let b_word = u64::from_le(core::ptr::read_unaligned(b_row.cast::<u64>()));
                if (b_word & m) == e {
                    let pp = partials[blk * 8 + $k].as_ptr();
                    #[allow(unused_mut)]
                    let mut db0 = vld1q_u8(pp);
                    #[allow(unused_mut)]
                    let mut db1 = vld1q_u8(pp.add(16));
                    #[allow(unused_mut)]
                    let mut db2 = vld1q_u8(pp.add(32));
                    #[allow(unused_mut)]
                    let mut db3 = vld1q_u8(pp.add(48));
                    $(
                        xor_vary_pair::<$j0, $j1>(
                            table_base,
                            half_swapped_table_base,
                            b_word,
                            &mut db0,
                            &mut db1,
                            &mut db2,
                            &mut db3,
                        );
                    )*
                    $(
                        xor_vary_single::<$js>(
                            table_base,
                            half_swapped_table_base,
                            b_word,
                            &mut db0,
                            &mut db1,
                            &mut db2,
                            &mut db3,
                        );
                    )*
                    if FAST {
                        fused_apply_one_k_with_b_fast::<{ $k & 1 }, { $k & 2 != 0 }>(
                            if $k & 4 != 0 { scaled_base } else { table_base },
                            if $k & 4 != 0 {
                                scaled_half_swapped_base
                            } else {
                                half_swapped_table_base
                            },
                            a_row,
                            db0,
                            db1,
                            db2,
                            db3,
                            &mut acc0_lo,
                            &mut acc0_hi,
                            &mut acc1_lo,
                            &mut acc1_hi,
                            &mut acc2_lo,
                            &mut acc2_hi,
                            &mut acc3_lo,
                            &mut acc3_hi,
                        );
                    } else {
                        fused_apply_one_k_with_b::<$k>(
                            table_base,
                            half_swapped_table_base,
                            a_row,
                            db0,
                            db1,
                            db2,
                            db3,
                            &mut acc0_lo,
                            &mut acc0_hi,
                            &mut acc1_lo,
                            &mut acc1_hi,
                            &mut acc2_lo,
                            &mut acc2_hi,
                            &mut acc3_lo,
                            &mut acc3_hi,
                        );
                    }
                } else {
                    k_generic!($k);
                }
            }};
        }
        match blk {
            0 => {
                k_static!(0, [], []);
                k_static!(1, [], []);
                k_static!(2, [], []);
                k_static!(3, [], []);
                k_static!(4, [], []);
                k_static!(5, [], []);
                k_static!(6, [], []);
                k_static!(7, [], []);
            }
            1 => {
                k_static!(0, [], []);
                k_static!(1, [], []);
                k_static!(2, [], []);
                k_static!(3, [], []);
                k_static!(4, [], []);
                k_static!(5, [], []);
                k_static!(6, [], []);
                k_static!(7, [], []);
            }
            2 => {
                k_static!(0, [], []);
                k_static!(1, [], []);
                k_generic!(2);
                k_generic!(3);
                k_generic!(4);
                k_static!(5, [], [7]);
                k_generic!(6);
                k_generic!(7);
            }
            3 => {
                k_generic!(0);
                k_static!(1, [(6, 7)], []);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1), (2, 3), (4, 5)], []);
                k_static!(5, [(5, 6)], [7]);
                k_generic!(6);
                k_generic!(7);
            }
            4 => {
                k_static!(0, [(0, 1), (2, 3), (4, 5)], []);
                k_static!(1, [(5, 6)], [7]);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1), (2, 3)], [4]);
                k_static!(5, [(4, 5), (6, 7)], []);
                k_generic!(6);
                k_generic!(7);
            }
            5 => {
                k_static!(0, [(0, 1), (2, 3)], []);
                k_static!(1, [(3, 4), (5, 6)], [7]);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1)], [2]);
                k_static!(5, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(6);
                k_generic!(7);
            }
            6 => {
                k_static!(0, [(0, 1)], [2]);
                k_static!(1, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1)], []);
                k_generic!(5);
                k_generic!(6);
                k_generic!(7);
            }
            7 => {
                k_static!(0, [], [0]);
                k_generic!(1);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [], [7]);
                k_generic!(5);
                k_generic!(6);
                k_generic!(7);
            }
            8 => {
                k_static!(0, [], [7]);
                k_generic!(1);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(6, 7)], []);
                k_generic!(5);
                k_generic!(6);
                k_static!(7, [(0, 1), (2, 3), (4, 5)], []);
            }
            9 => {
                k_static!(0, [(5, 6)], [7]);
                k_generic!(1);
                k_generic!(2);
                k_static!(3, [(0, 1), (2, 3)], [4]);
                k_static!(4, [(4, 5), (6, 7)], []);
                k_generic!(5);
                k_generic!(6);
                k_static!(7, [(0, 1), (2, 3)], [4]);
            }
            10 => {
                k_static!(0, [(4, 5), (6, 7)], []);
                k_generic!(1);
                k_generic!(2);
                k_static!(3, [(0, 1), (2, 3)], []);
                k_static!(4, [(3, 4), (5, 6)], [7]);
                k_generic!(5);
                k_generic!(6);
                k_static!(7, [(0, 1)], [2]);
            }
            11 => {
                k_static!(0, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(1);
                k_generic!(2);
                k_static!(3, [(0, 1)], []);
                k_generic!(4);
                k_generic!(5);
                k_generic!(6);
                k_static!(7, [(0, 1)], []);
            }
            12 => {
                k_generic!(0);
                k_generic!(1);
                k_generic!(2);
                k_static!(3, [], [0]);
                k_generic!(4);
                k_generic!(5);
                k_generic!(6);
                k_static!(7, [], [7]);
            }
            13 => {
                k_generic!(0);
                k_generic!(1);
                k_generic!(2);
                k_static!(3, [(6, 7)], []);
                k_generic!(4);
                k_generic!(5);
                k_generic!(6);
                k_static!(7, [(6, 7)], []);
            }
            14 => {
                k_generic!(0);
                k_generic!(1);
                k_static!(2, [(0, 1), (2, 3), (4, 5)], []);
                k_static!(3, [(5, 6)], [7]);
                k_generic!(4);
                k_generic!(5);
                k_static!(6, [(0, 1), (2, 3)], [4]);
                k_static!(7, [(4, 5), (6, 7)], []);
            }
            15 => {
                k_generic!(0);
                k_generic!(1);
                k_static!(2, [(0, 1), (2, 3)], []);
                k_static!(3, [(3, 4), (5, 6)], [7]);
                k_generic!(4);
                k_generic!(5);
                k_static!(6, [(0, 1), (2, 3)], []);
                k_static!(7, [(3, 4), (5, 6)], [7]);
            }
            16 => {
                k_generic!(0);
                k_generic!(1);
                k_static!(2, [(0, 1)], [2]);
                k_static!(3, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(4);
                k_generic!(5);
                k_static!(6, [(0, 1)], []);
                k_generic!(7);
            }
            17 => {
                k_generic!(0);
                k_generic!(1);
                k_static!(2, [], [0]);
                k_generic!(3);
                k_generic!(4);
                k_generic!(5);
                k_static!(6, [], [0]);
                k_generic!(7);
            }
            18 => {
                k_generic!(0);
                k_generic!(1);
                k_static!(2, [], [7]);
                k_generic!(3);
                k_generic!(4);
                k_generic!(5);
                k_static!(6, [(6, 7)], []);
                k_generic!(7);
            }
            19 => {
                k_generic!(0);
                k_static!(1, [(0, 1), (2, 3), (4, 5)], []);
                k_static!(2, [(5, 6)], [7]);
                k_generic!(3);
                k_generic!(4);
                k_static!(5, [(0, 1), (2, 3), (4, 5)], []);
                k_static!(6, [(5, 6)], [7]);
                k_generic!(7);
            }
            20 => {
                k_generic!(0);
                k_static!(1, [(0, 1), (2, 3)], [4]);
                k_static!(2, [(4, 5), (6, 7)], []);
                k_generic!(3);
                k_generic!(4);
                k_static!(5, [(0, 1), (2, 3)], []);
                k_static!(6, [(3, 4), (5, 6)], [7]);
                k_generic!(7);
            }
            21 => {
                k_generic!(0);
                k_static!(1, [(0, 1)], [2]);
                k_static!(2, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(3);
                k_generic!(4);
                k_static!(5, [(0, 1)], [2]);
                k_static!(6, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(7);
            }
            22 => {
                k_generic!(0);
                k_static!(1, [(0, 1)], []);
                k_generic!(2);
                k_generic!(3);
                k_generic!(4);
                k_static!(5, [], [0]);
                k_generic!(6);
                k_generic!(7);
            }
            23 => {
                k_generic!(0);
                k_static!(1, [], [7]);
                k_generic!(2);
                k_generic!(3);
                k_generic!(4);
                k_static!(5, [], [7]);
                k_generic!(6);
                k_generic!(7);
            }
            24 => {
                k_generic!(0);
                k_static!(1, [(6, 7)], []);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1), (2, 3), (4, 5)], []);
                k_static!(5, [(5, 6)], [7]);
                k_generic!(6);
                k_generic!(7);
            }
            25 => {
                k_static!(0, [(0, 1), (2, 3)], [4]);
                k_static!(1, [(4, 5), (6, 7)], []);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1), (2, 3)], [4]);
                k_static!(5, [(4, 5), (6, 7)], []);
                k_generic!(6);
                k_generic!(7);
            }
            26 => {
                k_static!(0, [(0, 1), (2, 3)], []);
                k_static!(1, [(3, 4), (5, 6)], [7]);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1)], [2]);
                k_static!(5, [(2, 3), (4, 5), (6, 7)], []);
                k_generic!(6);
                k_generic!(7);
            }
            27 => {
                k_static!(0, [(0, 1)], []);
                k_generic!(1);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [(0, 1)], []);
                k_generic!(5);
                k_generic!(6);
                k_generic!(7);
            }
            28 => {
                k_static!(0, [], [0]);
                k_generic!(1);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [], [7]);
                k_generic!(5);
                k_generic!(6);
                k_generic!(7);
            }
            29 => {
                k_static!(0, [(6, 7)], []);
                k_generic!(1);
                k_generic!(2);
                k_generic!(3);
                k_static!(4, [], []);
                k_static!(5, [], []);
                k_static!(6, [], []);
                k_static!(7, [], []);
            }
            30 => {
                k_static!(0, [], []);
                k_static!(1, [], []);
                k_static!(2, [], []);
                k_static!(3, [], []);
                k_static!(4, [], []);
                k_static!(5, [], []);
                k_static!(6, [], []);
                k_static!(7, [], []);
            }
            _ => return false,
        }
        let r0 = gf8_reduce_vec16(vreinterpretq_u8_u16(acc0_lo), vreinterpretq_u8_u16(acc0_hi));
        let r1 = gf8_reduce_vec16(vreinterpretq_u8_u16(acc1_lo), vreinterpretq_u8_u16(acc1_hi));
        let r2 = gf8_reduce_vec16(vreinterpretq_u8_u16(acc2_lo), vreinterpretq_u8_u16(acc2_hi));
        let r3 = gf8_reduce_vec16(vreinterpretq_u8_u16(acc3_lo), vreinterpretq_u8_u16(acc3_hi));
        store_row_64(out.as_mut_ptr(), nt_store, r0, r1, r2, r3);
    }
    true
}
