#!/usr/bin/env python3
"""Expand the fixed BLAKE3 round loop in the Apple 12-leaf kernel.

The input is the checked-in Apple-clang output from the original three-state
kernel. Keeping that compiler allocation as the template is deliberate: it
preserves the measured 12-leaf instruction-level parallelism and its exact
spill plan. This generator only substitutes the seven fixed message schedules
as immediate load offsets and duplicates the round body.
"""

from pathlib import Path


HERE = Path(__file__).resolve().parent
SOURCE = HERE / "blake3_neon12_looped_macos.S.in"
OUTPUT = HERE / "blake3_neon12_macos.S"

SCHEDULES = (
    (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
    (2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8),
    (3, 4, 10, 12, 13, 2, 7, 14, 6, 5, 9, 0, 11, 15, 8, 1),
    (10, 7, 12, 9, 14, 3, 13, 15, 4, 0, 11, 2, 5, 8, 1, 6),
    (12, 13, 9, 11, 15, 10, 14, 8, 7, 2, 5, 3, 0, 1, 6, 4),
    (9, 14, 11, 5, 8, 12, 15, 1, 13, 3, 0, 10, 2, 6, 4, 7),
    (11, 15, 5, 0, 1, 9, 8, 6, 14, 10, 2, 12, 3, 4, 7, 13),
)

# (two-instruction runtime index setup, address register, schedule slot).
# The compiler visits even columns first, then odd columns, so source order is
# not schedule order. Each address register must occur exactly once under each
# of the three transposed-message bases x9/x10/x11.
INDEX_SETUPS = (
    ("\tldurb\tw8, [x5, #-7]\n\tlsl\tx15, x8, #4\n", "x15", 0),
    ("\tldurb\tw8, [x5, #-5]\n\tlsl\tx8, x8, #4\n", "x8", 2),
    ("\tldurb\tw13, [x5, #-3]\n\tlsl\tx3, x13, #4\n", "x3", 4),
    ("\tldurb\tw13, [x5, #-1]\n\tlsl\tx6, x13, #4\n", "x6", 6),
    ("\tldurb\tw13, [x5, #-6]\n\tlsl\tx16, x13, #4\n", "x16", 1),
    ("\tldurb\tw13, [x5, #-4]\n\tlsl\tx17, x13, #4\n", "x17", 3),
    ("\tldurb\tw13, [x5, #-2]\n\tlsl\tx2, x13, #4\n", "x2", 5),
    ("\tldrb\tw13, [x5]\n\tlsl\tx4, x13, #4\n", "x4", 7),
    ("\tldrb\tw13, [x5, #1]\n\tlsl\tx1, x13, #4\n", "x1", 8),
    ("\tldrb\tw13, [x5, #3]\n\tlsl\tx0, x13, #4\n", "x0", 10),
    ("\tldrb\tw13, [x5, #5]\n\tlsl\tx20, x13, #4\n", "x20", 12),
    ("\tldrb\tw13, [x5, #7]\n\tlsl\tx21, x13, #4\n", "x21", 14),
    ("\tldrb\tw13, [x5, #2]\n\tlsl\tx13, x13, #4\n", "x13", 9),
    ("\tldrb\tw22, [x5, #4]\n\tlsl\tx22, x22, #4\n", "x22", 11),
    ("\tldrb\tw23, [x5, #6]\n\tlsl\tx23, x23, #4\n", "x23", 13),
    ("\tldrb\tw24, [x5, #8]\n\tlsl\tx24, x24, #4\n", "x24", 15),
)

ROUND_LABEL = "Lflock_b3_bb4:\n"
ROUND_BACKEDGE = (
    "\tadd\tx5, x5, #16\n"
    "\tsubs\tx14, x14, #1\n"
    "\tb.ne\tLflock_b3_bb4\n"
)
SCHEDULE_BASE_SETUP = (
    "Lflock_b3_loh2:\n"
    "\tadrp\tx5, Lflock_b3_msg_schedule@PAGE+7\n"
    "Lflock_b3_loh3:\n"
    "\tadd\tx5, x5, Lflock_b3_msg_schedule@PAGEOFF+7\n"
    "\tmov\tw14, #7\n"
)
SCHEDULE_LOH = "\t.loh AdrpAdd\tLflock_b3_loh2, Lflock_b3_loh3\n"
SCHEDULE_SECTION = "\t.section\t__TEXT,__const\nLflock_b3_msg_schedule:\n"


def replace_once(text: str, old: str, new: str, description: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one {description}, found {count}")
    return text.replace(old, new, 1)


def specialize_round(template: str, schedule: tuple[int, ...]) -> str:
    body = template
    for setup, register, slot in INDEX_SETUPS:
        body = replace_once(body, setup, "", f"setup for schedule slot {slot}")
        offset = schedule[slot] * 16
        for base in ("x9", "x10", "x11"):
            old = f"[{base}, {register}]"
            new = f"[{base}, #{offset}]"
            body = replace_once(body, old, new, f"{base}/{register} message load")
    return body


def generate(source: str) -> str:
    source = replace_once(source, SCHEDULE_BASE_SETUP, "", "schedule base setup")
    source = replace_once(source, SCHEDULE_LOH, "", "schedule LOH directive")

    prefix, remainder = source.split(ROUND_LABEL, 1)
    round_template, suffix = remainder.split(ROUND_BACKEDGE, 1)
    rounds = []
    for index, schedule in enumerate(SCHEDULES):
        rounds.append(f"\t// Fixed BLAKE3 message schedule, round {index}.\n")
        rounds.append(specialize_round(round_template, schedule))
    source = prefix + ROUND_LABEL + "".join(rounds) + suffix

    const_prefix, const_remainder = source.split(SCHEDULE_SECTION, 1)
    _, const_suffix = const_remainder.split(".subsections_via_symbols\n", 1)
    source = const_prefix + ".subsections_via_symbols\n" + const_suffix

    return "\t// Generated by blake3_neon12_unroll.py; do not edit.\n" + source


def main() -> None:
    OUTPUT.write_text(generate(SOURCE.read_text()))


if __name__ == "__main__":
    main()
